### ISSUE TITLE
Google update server does not always respond with latest 109 stable

### ISSUE THREAD

**Issue by jay** [shawnkhall/Tools#4]
I found your script on the Google enterprise forum. I used it this evening to access the [latest 109 stable](https://chromereleases.googleblog.com/2023/04/stable-channel-desktop-update.html) for Windows Server 2012 by using the command in your README:

~~~
.\ChromeDownloader.ps1 win 64 -os 2012 -do info
~~~

I noticed it was not 100% reproducible though. Sometimes Google returns 109.0.5414.129 and sometimes it returns 109.0.5414.141. When it returns the latter it is tagged as cohort "rampup" so there may be intentional behavior to randomly limit how many people initially get offered the latest 109.

I can reproduce without your script and so I reported this issue to Google. https://bugs.chromium.org/p/chromium/issues/detail?id=1439718

**Comment by shawnkhall** [comment]
Thank you, @jay . Google releases all products in a staged release cycle. Some devices are randomly pushed into early release as a form of public beta (or opted in via settings). Others won't get it until the version has operated without significant flaws for a given period. I don't think there's any public documentation on how long these periods last, but I suspect it's a week for most builds of Chrome -- based on my monitoring of releases since I wrote the first version of this script and the way they word the ["coming days/weeks" text in the release notes](https://chromereleases.googleblog.com/2023/04/stable-channel-desktop-update.html). Since Google releases most public versions on Tuesdays, it'll probably be pushed out to everyone tomorrow.

**Comment by jay** [comment]
Makes sense. Thanks
