### ISSUE TITLE
how to download latest 109 enterprise msi?

### ISSUE THREAD

**Issue by wgalafassijr** [shawnkhall/Tools#8]
Hi,

how to download latest 109 enterprise msi?

**Comment by shawnkhall** [comment]
I'm afraid that the MSI is only available for the "current" release channel, which means that the [v109 updates are only available](https://github.com/shawnkhall/Tools/issues/5#issuecomment-1533566956) as an EXE install/upgrade package. Like you, my goal was to be able to find MSIs for this since they're usually much easier to deploy. That's not an option.

The syntax for the exe packages is quite simple though:

    "c:\packages\{file}" --do-not-launch-chrome --channel=stable --system-level --create-shortcuts=2 --install-level=1


If you want to wait for it to finish before proceeding use the start command:

    start "" /D "c:\packages" /WAIT "{file}" --do-not-launch-chrome --channel=stable --system-level --create-shortcuts=2 --install-level=1

Replace "{file}" with the filename from the Chrome v109 exe you downloaded.
